### ISSUE TITLE
Expose more functions at API for bodies

### ISSUE THREAD

**Issue by Ughuuu** [erincatto/box2c#122] opened 2024-02-25 10:46 UTC
The following functions aren't exposed and the body can't change these unless destroyed and recreated.

void b2Body::SetBullet(bool flag);
bool b2Body::IsBullet() const;

void b2Body::SetAwake(bool flag);

void b2Body::SetFixedRotation(bool flag);
bool b2Body::IsFixedRotation() const;

**Comment by erincatto** [comment] 2024-02-25 21:15
Duplicate of #111

**Closed by erincatto** 2024-02-25 21:15 UTC
